server:
    port: 8082
    address: localhost

https:
    port: 8445

spring:
  profiles: prod
  thymeleaf:
    mode: XHTML
    cache: true
  mail:
    host: localhost
    port: 25
    user:
    password:
    protocol: smtp
    tls: false
    auth: false
  messageSource:
    cacheSeconds: 1

mongodb:
  url: localhost:27017
  databaseName: mica
  username:
  password:

opal:
  url: https://localhost:8443
  username: administrator
  password: password

shiro:
  obibaRealm:
    url: https://localhost:8444
    service:
      name: mica
      key: changeit
  password:
    nbHashIterations: 10000
    salt: mica

elasticsearch:
  dataNode: true
  clusterName: mica
  shards: 5
  replicas: 1
  settings: "http.enabled: false"

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

# Disable the spring security default configuration from spring-boot-actuator
#management.security.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
#jhipster.security.rememberme.key: mica

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

authentication:
    oauth:
        clientid: jhipsterapp
        secret: mySecretOAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800
