server:
    port: 8080
    address: localhost

spring:
    profiles: dev

    mongodb:
        url: localhost:27017
        databaseName: mica
        username:
        password:

    thymeleaf:
        mode: XHTML
        cache: false

shiro:
  password:
    nbHashIterations: 10000
    salt: mica

elasticsearch:
  dataNode: true
  clusterName: mica
  settings:

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600

# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: org.obiba.mica
      domain: org.obiba.mica.domain
      restdto: org.obiba.mica.web.rest.dto
    watchdir:
      - target/classes