server:
    port: 8080
    address: localhost

spring:
    profiles: prod

    mongodb:
        url: localhost:27017
        databaseName: mica
        username:
        password:

    thymeleaf:
        mode: XHTML
        cache: true

shiro:
  password:
    nbHashIterations: 10000
    salt: mica

elasticsearch:
  dataNode: true
  clusterName: mica
  settings:

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache:
    timeToLiveSeconds: 3600